### ISSUE TITLE
Default values werden nicht korrekt festgelegt

### ISSUE THREAD

**Issue by pointout** [cgoIT/contao-calendar-ical-bundle#14]
Ich bekomme eine Fehlermeldung, beim Import aus einer ics-Datei. Ich dachte erst es kommt vor Registrierungserweiterung.
Ich habe auch noch eigene Felder für Kalenderevents. Außerdem fehlt mir im DB Statement der Eventtitel aus der ical Datei.
Bitte schauen auf: https://github.com/inspiredminds/contao-event-registration/issues/16

Contao 4.9.40
cgoit/contao-calendar-ical-php8-bundle 4.4.9

**Comment by cgoIT** [comment]
Hi, leider fehlen mir da ein paar Informationen, um den Fehler nachvollziehen zu können.

- PHP Version
- Beispiel einer csv-Datei, bei der das Problem auftritt
- ggf. weitere Informationen zu den Settings des Kalenders

**Comment by fritzmg** [comment]
@cgoIT just add a nullable field:

```php
// contao/tl_calendar_events.php
$GLOBALS['TL_DCA']['tl_calendar_events']['fields']['foobar'] = [
    'sql' => ['type' => 'integer', 'unsigned' => true, 'notnull' => false],
];
```

Then import any calendar.

Currently `CalendarImport` sets the default value to `''` (if it wasn't determined otherwise) - which will of course be wrong for integer fields.

What you should do instead is _not_ fill all `tl_calendar_events` fields with a default value. Or only for those that define the default value in their DCA (by that I do _not_ mean the default value of the SQL definition!). For all other fields the default value is defined by their SQL definition and thus will be automatically filled if you insert a new record.

**Comment by cgoIT** [comment]
Hi @pointout,

ich habe mal eine fix gepushed. Könntest du bitte mal testen, ob das mit der Version dev-master funktioniert? Wenn ja, dann würde ich eine neue Version zur Verfügung stellen.

**Comment by pointout** [comment]
Ja, das funktioniert jetzt! Danke!
